language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
after_success:
  - npm i -g coveralls codeclimate-test-reporter
  - coveralls < coverage/lcov.info
  - codeclimate-test-reporter < coverage/lcov.info
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  script: npx semantic-release
  on:
    branch: master
